Repository parsec-cloud/libmatoya, pull requests merged in 2022-11, with the labels that each got.

#49 MTY_MoveFile fix + verbose test
  src/windows/filew.c
  test/file.h
Labels: 4. Impl. Reviewed

#53 MacOS pen barrel buttons fix
  src/unix/apple/macosx/app.m
Labels: 4. Impl. Reviewed

#11 Resolve IPv6
  src/net/net.c
  src/net/tcp.c
  src/net/tcp.h
Labels: 4. Impl. Reviewed

#66 Stop forcing fullscreen on new window
  src/unix/apple/macosx/app.m
Labels: 2. Review requested

#63 change permissions of lockfile
  src/unix/file.c
Labels: 3. 2nd review stage

#68 Fix relative mode
  src/unix/apple/macosx/app.m
Labels: 4. Impl. Reviewed

#45 WinInk/Physical barrel status switch
  src/unix/apple/iphoneos/app.m
  src/unix/apple/macosx/app.m
  src/unix/linux/android/app.c
  src/unix/linux/x11/app.c
  src/unix/web/app.c
  src/windows/appw.c
  src/windows/wintab.c
  src/windows/wintab.h
Labels: 3. 2nd review stage
