Repository parsec-cloud/libmatoya, pull requests merged in 2024-06, with the labels that each got.

#97 Async memory leak
  src/async.c
Labels: 4. Impl. Reviewed

#101 rookie mistake: calling strlen repeatedly inside a loop turns O(N) into O(N²)
  src/crypto.c
Labels: 4. Impl. Reviewed

#114 careless operator precedence mistake
  src/json.c
Labels: 2. Review requested

#116 [MacOS] More safety inside the websocket class
  src/unix/apple/ws.m
Labels: 2. Review requested

#108 Version-checking for WebView on macOS
  src/unix/apple/webview.m
Labels: 1. Coding

#118 Update version to 5.0
  src/matoya.h
Labels: 3. 2nd review stage

#120 MTY_QueueFlush improvement
  src/queue.c
Labels: 2. Review requested
