Repository parsec-cloud/libmatoya, pull requests merged in 2024-09, with the labels that each got.

#98 MTY_RWTryLockReader always blocks, acts same as MTY_RWLockReader
  src/thread.c
Labels: 3. 2nd review stage

#104 functions to convert unicode were not threadsafe except on Windows
  src/unix/memory.c
Labels: 3. 2nd review stage

#106 MTY_SprintfDL is unsafe, but is also very slow.
  src/memory.c
Labels: 3. 2nd review stage

#136 Do not access member of NULL ptr
  src/unix/linux/x11/app.c
Labels: 4. Impl. Reviewed

#133 [macOS - Improvement] Add compatibility with Karabiner Elements
  src/unix/apple/macosx/hid.c
Labels: 4. Impl. Reviewed

#134 [Windows - Improvement] Better checking of WebView2 availability
  src/windows/webview.c
Labels: 4. Impl. Reviewed

#131 this makes it possible to forbid optimizer & CPU from reordering loads & stores
  src/matoya.h
Labels: 3. 2nd review stage

#137 Wide-char array declaration has unnecessary extra wide-char size factor
  src/windows/dialog.c
Labels: 4. Impl. Reviewed

#135 Fix for audio playback on Windows clients going silent when audio device is invalidated
  src/windows/audio.c
Labels: 4. Impl. Reviewed, Test Matoya

#139 until now, there was no way to get a double in an object, using one of these macro things
  src/matoya.h
Labels: 3. 2nd review stage
